# .readthedocs.yaml aggiornato per il 2026
version: 2

build:
  # Aggiornato alla versione LTS più solida disponibile attualmente
  os: ubuntu-24.04
  tools:
    # Python 3.12 è lo standard di riferimento per stabilità e performance nel 2026
    python: "3.12"

# Configurazione Sphinx
sphinx:
  configuration: docs/conf.py

# Formati di output desiderati
formats:
  - pdf
  - epub 

# Installazione dipendenze
python:
  install:
    - requirements: docs/requirements.txt
